module.exports = {
  version: '0.2',
  language: 'en',
  words: [
    // general
    'nuxt',
    'nuxtjs',
    'vuetify',
    'vuex',
    'vuepress',
    'jscoverage',
    'toastify',
    'tailwindcss',
    // projects
    'BTCUSDT',
  ],
  flagWords: [],
  ignoreWords: [],
  ignorePaths: ['yarn.lock', 'static/images/banner.webp'],
  allowCompoundWords: true,
  import: [],
  dictionaries: [
    'vue',
    'javascript',
    'typescript',
    'css',
    'html',
    'html-symbol-entities',
    'npm',
    'node',
    'fullstack',
    'fonts',
    'filetypes',
    'softwareTerms',
    'dockerfile',
    'markdown',
    'xml',
    'yaml',
    'bash',
    'powershell',
    'cpp',
    'c',
    'json',
    'jsonc',
    'plaintext',
    'aws',
    'public-licenses',
    'cryptocurrencies',
    'companies',
    'misc',
    'en-gb',
    'lorem-ipsum',
  ],
}
